// src/components/LineStationPicker.vue
<template>
  <div>
    <Card>
      <Pick name="Line" :selected-id="line" :selected-name="selectedLineName" :enabled="true">
        <li v-for="option in linesData || []" :key="option.id">
          <RouterLink class="text-blue-800" :to="`/${option.id}`">
            {{ option.text }}
          </RouterLink>
        </li>
      </Pick>
    </Card>

    <Card>
      <div v-if="stationsError">Error {{ JSON.stringify(stationsError) }}</div>
      <Pick
        name="Station"
        :selected-id="station"
        :selected-name="selectedStationName"
        :enabled="!!line"
        :unselect-href="line ? `/${line}` : '/'"
      >
        <li v-for="option in stationsData || []" :key="option.id">
          <RouterLink class="text-blue-800" :to="`/${line}/${option.id}`">
            {{ option.text }}
          </RouterLink>
        </li>
      </Pick>
    </Card>
  </div>
</template>

<script setup lang="ts">
import { computed, watch } from 'vue'
import { useAsyncState } from '@vueuse/core'
import { RouterLink } from 'vue-router'
import { getLinesAsync, getStationsAsync } from '../services/lines-service'
import Card from './Card.vue'
import Pick from './Pick.vue'

const props = defineProps<{
  line?: string
  station?: string
}>()

// Fetch lines
const {
  state: linesData,
  isLoading: linesLoading,
  error: linesError,
} = useAsyncState(getLinesAsync, null, {
  immediate: true,
})

// Fetch stations when line changes
const {
  state: stationsData,
  isLoading: stationsLoading,
  error: stationsError,
  execute: fetchStations,
} = useAsyncState(() => (props.line ? getStationsAsync(props.line) : Promise.resolve([])), null, {
  immediate: false,
})

watch(
  () => props.line,
  (newLine) => {
    if (newLine) {
      fetchStations()
    }
  },
  { immediate: true },
)

const selectedLineName = computed(() => {
  return linesData.value?.find((item) => item.id === props.line)?.text
})

const selectedStationName = computed(() => {
  return stationsData.value?.find((item) => item.id === props.station)?.text
})
</script>

// components/LineStationPicker.tsx
import React, { FC } from 'react';
import { Pick } from './Pick';
import { getLinesAsync, getStationsAsync } from '../services/lines-service';
import useSWR from 'swr';
import { serializeError } from 'serialize-error';
import Link from 'next/link';
import urlJoin from 'url-join';

export const LineStationPicker: FC<{
  line: any;
  station: any;
}> = ({ line, station }) => {
  const lineData = useSWR<any[]>('lines', getLinesAsync);

  if (lineData.error) {
    return <div>Error {JSON.stringify(serializeError(lineData.error))}</div>;
  }

  const stationData = useSWR<any[]>(
    line,
    (line) => line && getStationsAsync(line),
    {}
  );

  return (
    <div>
      {/* <pre>{JSON.stringify({ line, station })}</pre> */}

      <div className="card">
        <Pick
          name="Line"
          // options={lineData.data}
          selectedId={line}
          enabled={true}
        >
          {lineData.data?.map((option) => (
            <Link href="/[line]" as={urlJoin('/', option.id)} key={option.id}>
              <a>
                <li>{option.text}</li>
              </a>
            </Link>
          ))}
        </Pick>
      </div>

      <div className="card">
        {Boolean(stationData.error) && (
          <div>Error {JSON.stringify(serializeError(stationData.error))}</div>
        )}
        <Pick name="Station" selectedId={station} enabled={line ? true : false}>
          {stationData.data?.map((option) => (
            <Link
              href="/[line]/[station]"
              as={urlJoin('/', line, option.id)}
              key={option.id}
            >
              <a>
                <li>{option.text}</li>
              </a>
            </Link>
          ))}
        </Pick>
      </div>
    </div>
  );
};
