// src/components/Train.vue
<template>
  <tr>
    <td class="w-1/4 text-center">{{ data.type }} to {{ data.boundFor }}</td>
    <td class="w-1/4 text-center">{{ data.delayStatus }}</td>
    <td class="w-1/4 text-center">{{ data.nowPosition }}</td>
    <td class="w-1/4 text-center">
      <TrainTicker :stations-away="Number(data.stationsAway)" />
    </td>
  </tr>
</template>

<script setup lang="ts">
import type { TrainModel } from '../types/train-model'
import TrainTicker from './TrainTicker.vue'

const props = defineProps<{
  data: TrainModel
}>()
</script>

// components/Train.tsx
import React, { Component } from 'react';
import TrainTicker from './TrainTicker';
import { TrainModel } from '../interfaces/train-model';

export default class Train extends Component<{
  data: TrainModel;
}> {
  render() {
    var train = this.props.data;

    return (
      <tr>
        <td>
          {train.type} to {train.boundFor}
        </td>
        <td>{train.delayStatus}</td>
        <td>{train.nowPosition}</td>
        <td>
          <TrainTicker stationsAway={this.props.data.stationsAway} />
        </td>
      </tr>
    );
  }
}
