// src/components/MainApp.vue
<template>
  <div>
    <div class="sticky top-0 bg-white shadow">
      <div class="nav-container mx-auto max-w-2xl">
        <RouterLink to="/" class="mr-auto block text-blue-800">
          <h1
            class="bg-gradient-to-br from-blue-700 to-blue-400 bg-clip-text p-2 text-5xl font-extrabold text-transparent"
          >
            Train Check
          </h1>
        </RouterLink>
      </div>
    </div>
    <!-- TODO: figure out why this does not align to the center of the page quite exactly -->
    <div class="mx-auto max-w-2xl p-2">
      <LineStationPicker :line="line" :station="station" />
      <StationInfo v-if="line && station" :line="line" :station="station" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import { RouterLink } from 'vue-router'
import LineStationPicker from './LineStationPicker.vue'
import StationInfo from './StationInfo.vue'

const route = useRoute()

const line = computed(() => route.params.line as string | undefined)
const station = computed(() => route.params.station as string | undefined)
</script>

// src/components/MainApp.tsx
import Link from 'next/link';
import { Fragment } from 'react';
import Head from 'next/head';
import { LineStationPicker } from './LineStationPicker';
import { StationInfo } from './StationInfo';
import { NextPage } from 'next';
import { useRouter } from 'next/router';

export const MainApp: NextPage = () => {
  const router = useRouter();
  const { line, station } = router.query;

  return (
    <Fragment>
      <Head>
        <title>TrainCheck</title>
      </Head>

      <div className="sticky top-0 bg-white shadow">
        <div className="nav-container mx-auto max-w-2xl">
          <Link href="/">
            <a className="mr-auto block">
              <h1 className="bg-gradient-to-br from-blue-700 to-blue-400 bg-clip-text p-2 text-5xl font-extrabold text-transparent">
                Train Check
              </h1>
            </a>
          </Link>
        </div>
      </div>
      {/* TODO: figure out why this does not align to the center of the page quite exactly */}
      <div className="mx-auto max-w-2xl p-2">
        <LineStationPicker line={line} station={station} />
        {Boolean(line && station) && (
          <StationInfo line={line} station={station} />
        )}
      </div>
    </Fragment>
  );
};
