// components/StationInfo.tsx
import React, { Component, FunctionComponent } from 'react';
import LoadingIcon from './LoadingIcon';
import Trains from './Trains';
import { getTrainsAsync } from '../services/lines-service';
import useSWR from 'swr';

export const StationInfo: FunctionComponent<{
  line: any;
  station: any;
}> = ({ line, station }) => {
  const { data, error } = useSWR(JSON.stringify({ line, station }), () =>
    getTrainsAsync(line, station)
  );
  const loading = !data;

  if (error) {
    console.log('error', error);
    return <div>error occurred</div>;
  } else if (loading) {
    return <LoadingIcon />;
  } else {
    return (
      <div>
        <div className="card">
          <Trains name="Northbound" data={data?.trainsUp} />
        </div>
        <div className="card">
          <Trains name="Southbound" data={data?.trainsDown} />
        </div>
      </div>
    );
  }
};

// src/components/StationInfo.vue
<template>
  <div v-if="error">error occurred</div>
  <LoadingIcon v-else-if="loading" />
  <div v-else>
    <Card>
      <Trains name="Northbound" :data="data?.trainsUp || []" />
    </Card>
    <Card>
      <Trains name="Southbound" :data="data?.trainsDown || []" />
    </Card>
  </div>
</template>

<script setup lang="ts">
import { watch } from 'vue'
import { useAsyncState } from '@vueuse/core'
import { getTrainsAsync } from '../services/lines-service'
import Card from './Card.vue'
import Trains from './Trains.vue'
import LoadingIcon from './LoadingIcon.vue'

const props = defineProps<{
  line: string
  station: string
}>()

const {
  state: data,
  isLoading: loading,
  error,
  execute: fetchTrains,
} = useAsyncState(() => getTrainsAsync(props.line, props.station), null, {
  immediate: true,
  resetOnExecute: true,
})

watch([() => props.line, () => props.station], () => {
  if (props.line && props.station) {
    fetchTrains()
  }
})
</script>
