// components/Trains.tsx
import React, { FC } from 'react';
import { Train } from './Train';
import { TrainModel } from '../interfaces/train-model';

export const Trains: FC<{
  name: string;
  data: TrainModel[];
}> = ({ name, data }) => {
  var trains = data.map((train) => {
    return <Train data={train} key={train.no} />;
  });

  return (
    <div>
      <h1>{name}</h1>
      <table className="table">
        <tbody>{trains}</tbody>
      </table>
      {data.length === 0 ? 'No trains' : null}
    </div>
  );
};

// src/components/Trains.vue
<template>
  <div>
    <h1>{{ name }}</h1>
    <table class="my-2 w-full">
      <tbody>
        <Train v-for="train in data" :key="train.no" :data="train" />
      </tbody>
    </table>
    <div v-if="data.length === 0">No trains</div>
  </div>
</template>

<script setup lang="ts">
import type { TrainModel } from '../types/train-model'
import Train from './Train.vue'

defineProps<{
  name: string
  data: TrainModel[]
}>()
</script>
