// src/components/Train.vue
<template>
  <tr>
    <td class="w-1/4 text-center">{{ data.type }} to {{ data.boundFor }}</td>
    <td class="w-1/4 text-center">{{ data.delayStatus }}</td>
    <td class="w-1/4 text-center">{{ data.nowPosition }}</td>
    <td class="w-1/4 text-center">
      <TrainTicker :stations-away="Number(data.stationsAway)" />
    </td>
  </tr>
</template>

<script setup lang="ts">
import type { TrainModel } from '../types/train-model'
import TrainTicker from './TrainTicker.vue'

const props = defineProps<{
  data: TrainModel
}>()
</script>

// src/components/Train.tsx
import React, { FC } from 'react';
import { TrainTicker } from './TrainTicker';
import { TrainModel } from '../interfaces/train-model';

export const Train: FC<{
  data: TrainModel;
}> = ({ data }) => {
  const train = data;

  return (
    <tr>
      <td className="w-1/4 text-center">
        {train.type} to {train.boundFor}
      </td>
      <td className="w-1/4 text-center">{train.delayStatus}</td>
      <td className="w-1/4 text-center">{train.nowPosition}</td>
      <td className="w-1/4 text-center">
        <TrainTicker stationsAway={Number(data.stationsAway)} />
      </td>
    </tr>
  );
};
